### ISSUE TITLE
Support for cookies?

### ISSUE THREAD

**Issue by chadfurman** [diachedelic/mock-res#12]
Is there support for cookies?  The documentation doesn't mention this

**Comment by diachedelic** [comment]
I think so, insomuch as Cookies are just headers. The following example from the Node docs should work, let me know if it's doesn't:

```
response.setHeader('Set-Cookie', ['type=ninja', 'language=javascript']);

const setCookie = response.getHeader('set-cookie');
// setCookie is of type string[]
```

**Comment by diachedelic** [comment]
See also this module for parsing/serialising cookies: https://www.npmjs.com/package/cookie

**Comment by diachedelic** [comment]
I've lightly documented it here: https://github.com/diachedelic/mock-res/commit/ab14b002ec5f437e9f6a421d3fa2793dc183ac9c
